version: '3.8'

services:
  db:
    image: postgres:14.3
    container_name: sola-db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  migrator-local:
    container_name: sola-db-migrator
    build:
      context: .
      dockerfile: migration_local.Dockerfile
    restart: on-failure

  backup:
    build:
      context: .
      dockerfile: backup.Dockerfile
    container_name: sola-backup
    environment:
      DB_HOST: db
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
    volumes:
      - backup_data:/backups
    depends_on:
      - db
    restart: on-failure

  app:
    build:
      context: .
      dockerfile: app.Dockerfile
    container_name: sola
    environment:
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_PORT: ${DB_PORT}
      DB_HOST: db
      AUTH_USER: ${AUTH_USER}
      AUTH_PASS: ${AUTH_PASS}
      S3_ENDPOINT: ${S3_ENDPOINT}
      S3_BUCKET: ${S3_BUCKET}
      S3_ACCESS_KEY: ${S3_ACCESS_KEY}
      S3_SECRET_KEY: ${S3_SECRET_KEY}
      S3_REGION: ${S3_REGION}
      PUBLIC_S3_URL: ${PUBLIC_S3_URL}
    ports:
      - "8080:8080"
    depends_on:
      - db
      - minio

  minio:
    image: minio/minio
    container_name: sola-minio
    environment:
      MINIO_ROOT_USER: ${S3_ACCESS_KEY}
      MINIO_ROOT_PASSWORD: ${S3_SECRET_KEY}
      MINIO_SERVER_URL: "http://localhost:9000"
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000" # MinIO API
      - "9001:9001" # MinIO Web Console
    volumes:
      - minio_data:/data

  minio-client:
    image: bitnami/minio-client
    container_name: sola-minio-client
    depends_on:
      - minio
    entrypoint: [ "/bin/bash", "-c", "--" ]
    command: |
      "while true; do sleep 30; done"

  s3-init:
    build:
      context: .
      dockerfile: init_s3.Dockerfile
    container_name: sola-s3-init
    depends_on:
      - minio
    volumes:
      - ./images:/images
    environment:
      S3_ACCESS_KEY: ${S3_ACCESS_KEY}
      S3_SECRET_KEY: ${S3_SECRET_KEY}
      S3_BUCKET: ${S3_BUCKET}

volumes:
  postgres_data:
  backup_data:
  minio_data:
