version: '3.8'

services:
  db:
    image: postgres:14.3
    container_name: sola-db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  migrator-local:
    container_name: sola-db-migrator
    build:
      context: .
      dockerfile: migration_local.Dockerfile
    restart: on-failure

  backup:
    build:
      context: .
      dockerfile: backup.Dockerfile
    container_name: sola-backup
    environment:
      DB_HOST: db
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
    volumes:
      - backup_data:/backups
    depends_on:
      - db
    restart: on-failure

  app:
    build:
      context: .
      dockerfile: app.Dockerfile
    container_name: sola
    environment:
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_PORT: ${DB_PORT}
      DB_HOST: db
    ports:
      - "8080:8080"
    depends_on:
      - db

volumes:
  postgres_data:
  backup_data: