INSERT INTO cakes (description, price, weight, full_description) VALUES ('Chocolate Cake', 25, 400, 'A rich and moist chocolate cake made with premium cocoa, layered with velvety chocolate ganache and topped with dark chocolate shavings.');
INSERT INTO cakes (description, price, weight, full_description) VALUES ('Vanilla Cake', 20, 350, 'A classic vanilla cake with a light and fluffy texture, filled with creamy vanilla frosting and adorned with a hint of vanilla bean.');
INSERT INTO cakes (description, price, weight, full_description) VALUES ('Молочная девочка', 30, 750, 'Торт, который тает во рту. Вкуснейшие коржи из сгущённого молока и кремом "Пломбир"');
INSERT INTO cakes (description, price, weight, full_description) VALUES ('Орео торт', 24, 1000, 'Вкуснейший торт с хрустящими печеньками OREO. Влажные ванильные шифоновые бисквиты, шоколадный крем с кусочками печенья');
INSERT INTO cakes (description, price, weight, full_description) VALUES ('Красный бархат', 26, 800, 'Всеми любимый красный бархат. Важные красные коржики с вкуснейшим кремчизом');
INSERT INTO cakes (description, price, weight, full_description) VALUES ('Медовик', 35, 900, 'Торт, который напоминает детство. Ароматные воздушные медовые коржи со сливочно-сметанным кремом');
INSERT INTO cakes (description, price, weight, full_description) VALUES ('Морковный торт', 20, 650, 'Торт, который пахнет осенью. Пряные морковные коржи с кремчизом');
INSERT INTO cakes (description, price, weight, full_description) VALUES ('Банановый рай', 27, 800, 'Влажные шифоновые с бисквиты с прослойкой из свежих бананов , с нежнейшим банановым муссом, который просто тает во рту, и вкуснейшим кремчизом');
INSERT INTO cakes (description, price, weight, full_description) VALUES ('Летняя свежесть', 25, 500, 'Лёгкий летний тортик с приятным мятным послевкусием.  Шифоновые бисквиты , пропитанные малиновым сиропом, малиновый конфитюр дополняет простоту и красоту торта, а кремчиз с мятным сиропом делает его вкус особенным');
INSERT INTO cakes (description, price, weight, full_description) VALUES ('Сникерс', 23, 870, 'шоколадные шифоновые бисквиты с вкуснейшим кремчизом, с солёной карамелью и хрустящим ароматным арахисом');
INSERT INTO cakes (description, price, weight, full_description) VALUES ('Клубничный подарок', 19, 300, 'Торт, который пахнет летом. Шифоновые бисквиты  с прослойкой из свежей клубники и кремчизом');
INSERT INTO cakes (description, price, weight, full_description) VALUES ('Персик со сливками', 32, 1000, 'Обалденный персиковый тортик. Шифоновые бисквиты, пропитанные персиковым сиропом, прослойкой из натуральных персиков и кремчизом');
-- INSERT INTO cakes (description, price, weight, full_description) VALUES ('Mango Cake', 32, 500, 'A tropical mango cake made with fresh mangoes, layered with mango-flavored cream and decorated with mango slices.');
-- INSERT INTO cakes (description, price, weight, full_description) VALUES ('Marble Cake', 21, 350, 'A visually stunning marble cake combining swirls of chocolate and vanilla batter, creating a perfect blend of flavors.');
-- INSERT INTO cakes (description, price, weight, full_description) VALUES ('Tiramisu', 34, 550, 'An Italian classic made with layers of coffee-soaked sponge, mascarpone cream, and a dusting of cocoa powder.');
-- INSERT INTO cakes (description, price, weight, full_description) VALUES ('Red Wine Cake', 29, 600, 'A unique and rich red wine cake with a touch of cocoa, infused with the flavors of red wine and topped with a creamy glaze.');
-- INSERT INTO cakes (description, price, weight, full_description) VALUES ('Peanut Butter Cake', 30, 500, 'A peanut butter lover’s dream with layers of peanut butter frosting and a moist cake, topped with chopped peanuts.');
-- INSERT INTO cakes (description, price, weight, full_description) VALUES ('Almond Cake', 22, 400, 'A fragrant almond cake made with ground almonds, topped with a delicate almond glaze and sliced almonds.');
-- INSERT INTO cakes (description, price, weight, full_description) VALUES ('Orange Cake', 20, 350, 'A bright and citrusy orange cake with fresh orange zest and juice, topped with a zesty orange glaze.');
-- INSERT INTO cakes (description, price, weight, full_description) VALUES ('Raspberry Cake', 28, 450, 'A luscious raspberry cake with layers of raspberry-flavored sponge and cream, topped with fresh raspberries.');
-- INSERT INTO cakes (description, price, weight, full_description) VALUES ('Nut Cake', 35, 550, 'A hearty nut cake loaded with a variety of nuts, spiced batter, and a creamy nut-flavored frosting.');
-- INSERT INTO cakes (description, price, weight, full_description) VALUES ('Coconut Cake', 26, 400, 'A tropical coconut cake layered with coconut cream frosting and garnished with shredded coconut.');
-- INSERT INTO cakes (description, price, weight, full_description) VALUES ('Pistachio Cake', 31, 500, 'A light and nutty pistachio cake made with real pistachios, topped with a creamy pistachio frosting.');
-- INSERT INTO cakes (description, price, weight, full_description) VALUES ('Millefeuille', 27, 600, 'A French pastry classic with layers of flaky puff pastry, creamy custard, and a sugary glaze.');
-- INSERT INTO cakes (description, price, weight, full_description) VALUES ('Lavender Cake', 24, 350, 'A delicate lavender cake infused with floral lavender essence, paired with a light and creamy frosting.');
-- INSERT INTO cakes (description, price, weight, full_description) VALUES ('Matcha Cake', 29, 450, 'A Japanese-inspired matcha cake made with premium green tea powder, offering a unique earthy flavor.');
-- INSERT INTO cakes (description, price, weight, full_description) VALUES ('Frozen Yogurt Cake', 21, 300, 'A refreshing frozen yogurt cake with a creamy texture and a mix of tangy and sweet flavors.');
-- INSERT INTO cakes (description, price, weight, full_description) VALUES ('Ginger Cake', 19, 350, 'A spiced ginger cake with a warm flavor profile, enhanced with molasses and topped with a tangy icing.');
-- INSERT INTO cakes (description, price, weight, full_description) VALUES ('Zebra Cake', 26, 400, 'A fun zebra-patterned cake with alternating layers of chocolate and vanilla batter, creating a striking visual effect.');
-- INSERT INTO cakes (description, price, weight, full_description) VALUES ('Sponge Cake', 23, 500, 'A soft and airy sponge cake with a light texture, perfect as a base for various fillings and toppings.');
-- INSERT INTO cakes (description, price, weight, full_description) VALUES ('Cupcake', 15, 150, 'A cute and delicious individual-sized cupcake with moist cake and a swirl of creamy frosting.');
-- INSERT INTO cakes (description, price, weight, full_description) VALUES ('Baklava Cake', 30, 550, 'A fusion of traditional baklava and cake, with layers of nuts, honey, and spiced cake, topped with syrup.');
-- INSERT INTO cakes (description, price, weight, full_description) VALUES ('Ice Cream Cake', 33, 600, 'A delightful ice cream cake with layers of cake and creamy ice cream, perfect for any celebration.');


INSERT INTO delivery_points (address, rating, working_hours, contact_phone) VALUES ('123 Main St', 8, '9 AM - 9 PM', '555-0123');
INSERT INTO delivery_points (address, rating, working_hours, contact_phone) VALUES ('456 Oak St', 9, '10 AM - 8 PM', '555-0456');
INSERT INTO delivery_points (address, rating, working_hours, contact_phone) VALUES ('789 Pine St', 7, '11 AM - 7 PM', '555-0789');
INSERT INTO delivery_points (address, rating, working_hours, contact_phone) VALUES ('135 Maple Ave', 10, '8 AM - 10 PM', '555-1357');
INSERT INTO delivery_points (address, rating, working_hours, contact_phone) VALUES ('246 Elm St', 6, '9 AM - 9 PM', '555-2468');
INSERT INTO delivery_points (address, rating, working_hours, contact_phone) VALUES ('357 Birch Rd', 5, '10 AM - 6 PM', '555-3579');
INSERT INTO delivery_points (address, rating, working_hours, contact_phone) VALUES ('468 Cedar Blvd', 8, '8 AM - 8 PM', '555-4680');
INSERT INTO delivery_points (address, rating, working_hours, contact_phone) VALUES ('579 Spruce Ct', 9, '12 PM - 10 PM', '555-5791');
INSERT INTO delivery_points (address, rating, working_hours, contact_phone) VALUES ('680 Walnut St', 7, '9 AM - 5 PM', '555-6802');
INSERT INTO delivery_points (address, rating, working_hours, contact_phone) VALUES ('791 Cherry Ln', 10, '11 AM - 9 PM', '555-7913');
INSERT INTO delivery_points (address, rating, working_hours, contact_phone) VALUES ('902 Aspen Dr', 6, '10 AM - 4 PM', '555-9024');
INSERT INTO delivery_points (address, rating, working_hours, contact_phone) VALUES ('1 Oak St', 8, '9 AM - 9 PM', '555-0001');
INSERT INTO delivery_points (address, rating, working_hours, contact_phone) VALUES ('2 Walnut St', 7, '10 AM - 8 PM', '555-0002');
INSERT INTO delivery_points (address, rating, working_hours, contact_phone) VALUES ('3 Pine St', 9, '11 AM - 9 PM', '555-0003');
INSERT INTO delivery_points (address, rating, working_hours, contact_phone) VALUES ('4 Maple Ave', 10, '8 AM - 10 PM', '555-0004');
INSERT INTO delivery_points (address, rating, working_hours, contact_phone) VALUES ('5 Elm St', 6, '10 AM - 6 PM', '555-0005');
INSERT INTO delivery_points (address, rating, working_hours, contact_phone) VALUES ('6 Cedar Blvd', 5, '9 AM - 9 PM', '555-0006');
INSERT INTO delivery_points (address, rating, working_hours, contact_phone) VALUES ('7 Birch Rd', 8, '12 PM - 6 PM', '555-0007');
INSERT INTO delivery_points (address, rating, working_hours, contact_phone) VALUES ('8 Spruce Ct', 9, '9 AM - 8 PM', '555-0008');
INSERT INTO delivery_points (address, rating, working_hours, contact_phone) VALUES ('9 Cherry Ln', 7, '11 AM - 10 PM', '555-0009');
INSERT INTO delivery_points (address, rating, working_hours, contact_phone) VALUES ('10 Aspen Dr', 10, '8 AM - 9 PM', '555-0010');
INSERT INTO delivery_points (address, rating, working_hours, contact_phone) VALUES ('11 Oak St', 6, '10 AM - 7 PM', '555-0011');
INSERT INTO delivery_points (address, rating, working_hours, contact_phone) VALUES ('12 Walnut St', 8, '9 AM - 6 PM', '555-0012');
INSERT INTO delivery_points (address, rating, working_hours, contact_phone) VALUES ('13 Pine St', 9, '11 AM - 9 PM', '555-0013');
INSERT INTO delivery_points (address, rating, working_hours, contact_phone) VALUES ('14 Maple Ave', 10, '8 AM - 10 PM', '555-0014');