INSERT INTO cakes (description, price, weight) VALUES ('Chocolate Cake', 25, 400);
INSERT INTO cakes (description, price, weight) VALUES ('Vanilla Cake', 20, 350);
INSERT INTO cakes (description, price, weight) VALUES ('Red Velvet Cake', 30, 450);
INSERT INTO cakes (description, price, weight) VALUES ('Lemon Cake', 18, 300);
INSERT INTO cakes (description, price, weight) VALUES ('Carrot Cake', 22, 400);
INSERT INTO cakes (description, price, weight) VALUES ('Cheesecake', 35, 500);
INSERT INTO cakes (description, price, weight) VALUES ('Black Forest Cake', 28, 600);
INSERT INTO cakes (description, price, weight) VALUES ('Fruit Cake', 20, 350);
INSERT INTO cakes (description, price, weight) VALUES ('Pineapple Cake', 24, 400);
INSERT INTO cakes (description, price, weight) VALUES ('Coffee Cake', 27, 500);
INSERT INTO cakes (description, price, weight) VALUES ('Brownie Cake', 23, 400);
INSERT INTO cakes (description, price, weight) VALUES ('Banana Cake', 19, 300);
INSERT INTO cakes (description, price, weight) VALUES ('Strawberry Cake', 26, 450);
INSERT INTO cakes (description, price, weight) VALUES ('Mango Cake', 32, 500);
INSERT INTO cakes (description, price, weight) VALUES ('Marble Cake', 21, 350);
INSERT INTO cakes (description, price, weight) VALUES ('Tiramisu', 34, 550);
INSERT INTO cakes (description, price, weight) VALUES ('Red Wine Cake', 29, 600);
INSERT INTO cakes (description, price, weight) VALUES ('Peanut Butter Cake', 30, 500);
INSERT INTO cakes (description, price, weight) VALUES ('Almond Cake', 22, 400);
INSERT INTO cakes (description, price, weight) VALUES ('Orange Cake', 20, 350);
INSERT INTO cakes (description, price, weight) VALUES ('Raspberry Cake', 28, 450);
INSERT INTO cakes (description, price, weight) VALUES ('Nut Cake', 35, 550);
INSERT INTO cakes (description, price, weight) VALUES ('Coconut Cake', 26, 400);
INSERT INTO cakes (description, price, weight) VALUES ('Pistachio Cake', 31, 500);
INSERT INTO cakes (description, price, weight) VALUES ('Millefeuille', 27, 600);
INSERT INTO cakes (description, price, weight) VALUES ('Lavender Cake', 24, 350);
INSERT INTO cakes (description, price, weight) VALUES ('Matcha Cake', 29, 450);
INSERT INTO cakes (description, price, weight) VALUES ('Frozen Yogurt Cake', 21, 300);
INSERT INTO cakes (description, price, weight) VALUES ('Ginger Cake', 19, 350);
INSERT INTO cakes (description, price, weight) VALUES ('Zebra Cake', 26, 400);
INSERT INTO cakes (description, price, weight) VALUES ('Sponge Cake', 23, 500);
INSERT INTO cakes (description, price, weight) VALUES ('Cupcake', 15, 150);
INSERT INTO cakes (description, price, weight) VALUES ('Baklava Cake', 30, 550);
INSERT INTO cakes (description, price, weight) VALUES ('Ice Cream Cake', 33, 600);


INSERT INTO delivery_points (address, rating, working_hours, contact_phone) VALUES ('123 Main St', 8, '9 AM - 9 PM', '555-0123');
INSERT INTO delivery_points (address, rating, working_hours, contact_phone) VALUES ('456 Oak St', 9, '10 AM - 8 PM', '555-0456');
INSERT INTO delivery_points (address, rating, working_hours, contact_phone) VALUES ('789 Pine St', 7, '11 AM - 7 PM', '555-0789');
INSERT INTO delivery_points (address, rating, working_hours, contact_phone) VALUES ('135 Maple Ave', 10, '8 AM - 10 PM', '555-1357');
INSERT INTO delivery_points (address, rating, working_hours, contact_phone) VALUES ('246 Elm St', 6, '9 AM - 9 PM', '555-2468');
INSERT INTO delivery_points (address, rating, working_hours, contact_phone) VALUES ('357 Birch Rd', 5, '10 AM - 6 PM', '555-3579');
INSERT INTO delivery_points (address, rating, working_hours, contact_phone) VALUES ('468 Cedar Blvd', 8, '8 AM - 8 PM', '555-4680');
INSERT INTO delivery_points (address, rating, working_hours, contact_phone) VALUES ('579 Spruce Ct', 9, '12 PM - 10 PM', '555-5791');
INSERT INTO delivery_points (address, rating, working_hours, contact_phone) VALUES ('680 Walnut St', 7, '9 AM - 5 PM', '555-6802');
INSERT INTO delivery_points (address, rating, working_hours, contact_phone) VALUES ('791 Cherry Ln', 10, '11 AM - 9 PM', '555-7913');
INSERT INTO delivery_points (address, rating, working_hours, contact_phone) VALUES ('902 Aspen Dr', 6, '10 AM - 4 PM', '555-9024');
INSERT INTO delivery_points (address, rating, working_hours, contact_phone) VALUES ('1 Oak St', 8, '9 AM - 9 PM', '555-0001');
INSERT INTO delivery_points (address, rating, working_hours, contact_phone) VALUES ('2 Walnut St', 7, '10 AM - 8 PM', '555-0002');
INSERT INTO delivery_points (address, rating, working_hours, contact_phone) VALUES ('3 Pine St', 9, '11 AM - 9 PM', '555-0003');
INSERT INTO delivery_points (address, rating, working_hours, contact_phone) VALUES ('4 Maple Ave', 10, '8 AM - 10 PM', '555-0004');
INSERT INTO delivery_points (address, rating, working_hours, contact_phone) VALUES ('5 Elm St', 6, '10 AM - 6 PM', '555-0005');
INSERT INTO delivery_points (address, rating, working_hours, contact_phone) VALUES ('6 Cedar Blvd', 5, '9 AM - 9 PM', '555-0006');
INSERT INTO delivery_points (address, rating, working_hours, contact_phone) VALUES ('7 Birch Rd', 8, '12 PM - 6 PM', '555-0007');
INSERT INTO delivery_points (address, rating, working_hours, contact_phone) VALUES ('8 Spruce Ct', 9, '9 AM - 8 PM', '555-0008');
INSERT INTO delivery_points (address, rating, working_hours, contact_phone) VALUES ('9 Cherry Ln', 7, '11 AM - 10 PM', '555-0009');
INSERT INTO delivery_points (address, rating, working_hours, contact_phone) VALUES ('10 Aspen Dr', 10, '8 AM - 9 PM', '555-0010');
INSERT INTO delivery_points (address, rating, working_hours, contact_phone) VALUES ('11 Oak St', 6, '10 AM - 7 PM', '555-0011');
INSERT INTO delivery_points (address, rating, working_hours, contact_phone) VALUES ('12 Walnut St', 8, '9 AM - 6 PM', '555-0012');
INSERT INTO delivery_points (address, rating, working_hours, contact_phone) VALUES ('13 Pine St', 9, '11 AM - 9 PM', '555-0013');
INSERT INTO delivery_points (address, rating, working_hours, contact_phone) VALUES ('14 Maple Ave', 10, '8 AM - 10 PM', '555-0014');