env: "local" #local, dev, prod
http_server:
  address: "localhost:8080"
  timeout: 4s         # read request time and the same send request time
  idle_timeout: 60s   # connection with client life time 
db:
  username: "postgres"
  password: "qwerty"
  address: "localhost:5432"
  dbname: "postgres"
  sslmode: "disable"